In [2]:
import numpy as np

In [5]:
#Create a null vector of size 10 but the fifth value which is 1.

arr = np.zeros(10,dtype = int)
arr[4] = 1

print(arr)

[0 0 0 0 1 0 0 0 0 0]


In [9]:
#Create a vector with values ranging from 10 to 49.

array1 = np.arange(10,50)
array1


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [23]:
#Create a 3x3 matrix with values ranging from 0 to 8

array = np.arange(0,9).reshape(3,3)
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [19]:
#Find indices of non-zero elements from [1,2,0,0,4,0]

x = np.nonzero([1,2,0,0,4,0])
print(x)

(array([0, 1, 4], dtype=int64),)


In [24]:
#Create a 10x10 array with random values and find the minimum and maximum values.

Y = np.random.random((10,10))
Ymin, Ymax = Y.min(), Y.max()
print(Ymin, Ymax)

0.020909203733819992 0.97954387627318


In [31]:
# Create a random vector of size 30 and find the mean value

X = np.random.random(30)
m = X.mean()
print(m)

0.4844144267543109
